version: '3.2'

services:
  nuxt:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"

  cypress:
    image: cypress/included:cypress-13.11.0-node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "3000:3000"
    command: npx cypress open
    depends_on:
      - nuxt
